env: production
timeZone: "Asia/Tehran"
log:
  enable: true
  level: 1
server:
  http:
    enable: true
    port: 2780
auth:
  internal:
    enable:
    method: 
    key: 
backend:
  app: 
  watcher:
  watcherPeriod:
  preferSecure:
  brokenThreshold: 1500
  server:
    tcp:
      enable:
      port: 
    tcp_s:
      enable:
      port: 
    grpc:
      enable:
      port: 
    grpc_s:
      enable:
      port: 
monitor:
  enable:
  track:
    latency:
    request:
    metric:
      cron: "0 0 * * *"
      topN: 10
  subscribe:
    telNotif:
      enable:
      token: 
      channelId: 
    log:
      enable:
server-list:
  persistStep:
rules:
  direct:
  -
