env: production
timeZone: "Asia/Tehran"
log:
  enable: true
  level: 1
server:
  http:
    enable: true
    port: 2780
auth:
  internal:
    enable: true
    method: 
    key: 
backend:
  app: 
  watcher: true
  watcherPeriod: "1m"
  preferSecure: false
  brokenThreshold: 1500
  server:
    tcp:
      enable: true
      port: 32001
    tcp_s:
      enable: false
      port: 32002
    grpc:
      enable: true
      port: 32003
    grpc_s:
      enable: false
      port: 32004
monitor:
  enable: true
  track:
    latency: true
    request: true
    metric:
      cron: "0 0 * * *"
      topN: 10
  subscribe:
    telNotif:
      enable: true
      token: 
      channelId: 
    log:
      enable: false
server-list:
  persistStep: 5
rules:
  direct:
  -
